# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1382609796);
user_pref("app.update.migrated.updateDir", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.popups.showPopupBlocker", false);
user_pref("browser.rights.3.shown", true);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.slowStartup.averageTime", 1357);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20130910201120");
user_pref("browser.startup.homepage_override.mstone", "24.0");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1407224336693");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1407224337817");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1407310737817");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1406711976172");
user_pref("datareporting.policy.firstRunTime", "1382609795819");
user_pref("datareporting.sessions.current.activeTicks", 18);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1116);
user_pref("datareporting.sessions.current.main", 52);
user_pref("datareporting.sessions.current.sessionRestored", 1144);
user_pref("datareporting.sessions.current.startTime", "1407224283958");
user_pref("datareporting.sessions.current.totalTime", 150);
user_pref("datareporting.sessions.currentIndex", 33);
user_pref("datareporting.sessions.previous.12", "{\"s\":1406108521336,\"a\":1,\"t\":3,\"c\":true,\"m\":90,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.13", "{\"s\":1406108525569,\"a\":2,\"t\":7,\"c\":true,\"m\":73,\"fp\":424,\"sr\":441}");
user_pref("datareporting.sessions.previous.14", "{\"s\":1406108534330,\"a\":1,\"t\":1,\"c\":true,\"m\":67,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.15", "{\"s\":1406119397664,\"a\":2,\"t\":8,\"c\":true,\"m\":1247,\"fp\":2564,\"sr\":2624}");
user_pref("datareporting.sessions.previous.16", "{\"s\":1406119681444,\"a\":4,\"t\":29,\"c\":true,\"m\":119,\"fp\":649,\"sr\":709}");
user_pref("datareporting.sessions.previous.17", "{\"s\":1406119762220,\"a\":4,\"t\":94,\"c\":true,\"m\":1371,\"fp\":2264,\"sr\":2282}");
user_pref("datareporting.sessions.previous.18", "{\"s\":1406119879845,\"a\":8,\"t\":1743,\"c\":true,\"m\":864,\"fp\":1439,\"sr\":1500}");
user_pref("datareporting.sessions.previous.19", "{\"s\":1406206044856,\"a\":10,\"t\":108,\"c\":true,\"m\":321,\"fp\":908,\"sr\":983}");
user_pref("datareporting.sessions.previous.20", "{\"s\":1406206205101,\"a\":1,\"t\":4,\"c\":true,\"m\":383,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.21", "{\"s\":1406207394388,\"a\":52,\"t\":2161,\"c\":true,\"m\":98,\"fp\":657,\"sr\":677}");
user_pref("datareporting.sessions.previous.22", "{\"s\":1406209590917,\"a\":3,\"t\":11,\"c\":true,\"m\":83,\"fp\":505,\"sr\":523}");
user_pref("datareporting.sessions.previous.23", "{\"s\":1406209688962,\"a\":49,\"t\":9924,\"c\":true,\"m\":100,\"fp\":515,\"sr\":533}");
user_pref("datareporting.sessions.previous.24", "{\"s\":1406532614983,\"a\":9,\"t\":84,\"c\":true,\"m\":1371,\"fp\":1994,\"sr\":2033}");
user_pref("datareporting.sessions.previous.25", "{\"s\":1406647967292,\"a\":9,\"t\":707,\"c\":true,\"m\":352,\"fp\":722,\"sr\":758}");
user_pref("datareporting.sessions.previous.26", "{\"s\":1406648796721,\"a\":1,\"t\":4,\"c\":true,\"m\":58,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.27", "{\"s\":1406648803767,\"a\":2,\"t\":6,\"c\":true,\"m\":137,\"fp\":478,\"sr\":494}");
user_pref("datareporting.sessions.previous.28", "{\"s\":1406648811880,\"a\":1,\"t\":2,\"c\":true,\"m\":41,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.29", "{\"s\":1406648817097,\"a\":1,\"t\":1,\"c\":true,\"m\":37,\"fp\":-1,\"sr\":-1}");
user_pref("datareporting.sessions.previous.30", "{\"s\":1406711204034,\"a\":17,\"t\":536,\"c\":true,\"m\":110,\"fp\":495,\"sr\":523}");
user_pref("datareporting.sessions.previous.31", "{\"s\":1406711914945,\"a\":17,\"t\":1616,\"c\":true,\"m\":67,\"fp\":447,\"sr\":464}");
user_pref("datareporting.sessions.previous.32", "{\"s\":1407156722754,\"a\":8,\"t\":40,\"c\":true,\"m\":116,\"fp\":503,\"sr\":552}");
user_pref("datareporting.sessions.prunedIndex", 11);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1382603363169,\"rdfTime\":1378874456000}}}]");
user_pref("extensions.lastAppVersion", "24.0");
user_pref("extensions.lastPlatformVersion", "24.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130910201120");
user_pref("gecko.mstone", "24.0");
user_pref("gfx.direct2d.disabled", true);
user_pref("intl.accept_languages", "en-gb,en");
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("layers.acceleration.disabled", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.popups.showBrowserMessage", false);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1382610319);
user_pref("toolkit.telemetry.previousBuildID", "20130910201120");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1385201803);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
